//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyServiceClient.NotifyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotifyServiceReference.INotificationService")]
    public interface INotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/StartServer", ReplyAction="http://tempuri.org/INotificationService/StartServerResponse")]
        string StartServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/StartServer", ReplyAction="http://tempuri.org/INotificationService/StartServerResponse")]
        System.Threading.Tasks.Task<string> StartServerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/StopServer", ReplyAction="http://tempuri.org/INotificationService/StopServerResponse")]
        string StopServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/StopServer", ReplyAction="http://tempuri.org/INotificationService/StopServerResponse")]
        System.Threading.Tasks.Task<string> StopServerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationServiceChannel : NotifyServiceClient.NotifyServiceReference.INotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationServiceClient : System.ServiceModel.ClientBase<NotifyServiceClient.NotifyServiceReference.INotificationService>, NotifyServiceClient.NotifyServiceReference.INotificationService {
        
        public NotificationServiceClient() {
        }
        
        public NotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StartServer() {
            return base.Channel.StartServer();
        }
        
        public System.Threading.Tasks.Task<string> StartServerAsync() {
            return base.Channel.StartServerAsync();
        }
        
        public string StopServer() {
            return base.Channel.StopServer();
        }
        
        public System.Threading.Tasks.Task<string> StopServerAsync() {
            return base.Channel.StopServerAsync();
        }
    }
}
